name: Enforce PR label

on:
  pull_request:
    branches:
      - master
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: yogevbd/enforce-label-action@2.2.2
        with:
          REQUIRED_LABELS_ANY: 'production,non-production'
          REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['production','non-production']"
